CREATE TABLE timetables (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    name varchar(255) NOT NULL,
    year integer NOT NULL,
    semester varchar(255) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE INDEX ix_timetables_user_id ON timetables (user_id);

CREATE TABLE timetable_courses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timetable_id bigint NOT NULL REFERENCES timetables(id) ON DELETE CASCADE,
    course_id bigint NOT NULL,
    course_name varchar(255) NOT NULL,
    professor_name varchar(255),
    credit integer NOT NULL,
    day_of_week varchar(20) NOT NULL,
    start_time time NOT NULL,
    end_time time NOT NULL,
    CONSTRAINT ck_timetable_courses_day CHECK (
        day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
    )
);

CREATE INDEX ix_timetable_courses_timetable_id ON timetable_courses (timetable_id);

COMMENT ON TABLE timetables IS
    '사용자가 만든 시간표 한 벌(연도/학기 단위).';
COMMENT ON TABLE timetable_courses IS
    'TimetableCourse: 시간표에 담긴 강의(분반)의 요일-시간 슬롯 스냅샷. 한 강의가 여러 요일에 걸치면 같은 course_id 로 여러 행이 생긴다.';
