ALTER TABLE catalog_sources
    ADD COLUMN supplemental_row_count integer NOT NULL DEFAULT 0,
    ADD CONSTRAINT ck_catalog_sources_supplemental_count
        CHECK (supplemental_row_count >= 0);

CREATE TABLE catalog_program_course_listings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_checksum varchar(64) NOT NULL
        REFERENCES catalog_sources(checksum) ON DELETE CASCADE,
    semester_id varchar(20) NOT NULL,
    program_kind varchar(40) NOT NULL,
    college_name text NOT NULL,
    program_name text NOT NULL,
    course_name text NOT NULL,
    offering_unit_label text NOT NULL,
    offering_academic_unit_code varchar(40)
        REFERENCES academic_units(code) ON DELETE RESTRICT,
    catalog_page_label varchar(20) NOT NULL,
    is_offered boolean NOT NULL,
    resolution_status varchar(24) NOT NULL,
    course_code varchar(40),
    source_page integer NOT NULL,
    source_row integer NOT NULL,
    raw_cells jsonb NOT NULL,
    CONSTRAINT fk_catalog_program_course
        FOREIGN KEY (semester_id, course_code)
        REFERENCES courses(semester_id, course_code)
        ON DELETE CASCADE,
    CONSTRAINT ck_catalog_program_kind CHECK (
        program_kind IN ('MICRO_MAJOR')
    ),
    CONSTRAINT ck_catalog_program_source_page CHECK (source_page > 0),
    CONSTRAINT ck_catalog_program_source_row CHECK (source_row > 0),
    CONSTRAINT ck_catalog_program_resolution_status CHECK (
        resolution_status IN (
            'RESOLVED',
            'NOT_OFFERED',
            'SOURCE_NOT_FOUND',
            'AMBIGUOUS'
        )
    ),
    CONSTRAINT ck_catalog_program_resolution CHECK (
        (resolution_status = 'RESOLVED' AND is_offered AND course_code IS NOT NULL)
        OR (
            resolution_status = 'NOT_OFFERED'
            AND NOT is_offered
            AND course_code IS NULL
        )
        OR (
            resolution_status IN ('SOURCE_NOT_FOUND', 'AMBIGUOUS')
            AND is_offered
            AND course_code IS NULL
        )
    ),
    CONSTRAINT uq_catalog_program_source
        UNIQUE (source_checksum, source_page, source_row)
);

CREATE INDEX ix_catalog_program_name
    ON catalog_program_course_listings (
        semester_id,
        program_name,
        course_name
    );

CREATE INDEX ix_catalog_program_course
    ON catalog_program_course_listings (semester_id, course_code)
    WHERE course_code IS NOT NULL;

COMMENT ON TABLE catalog_program_course_listings IS
    'Micro-major appendix rows, including offered and explicitly not-offered course entries.';
