CREATE FUNCTION normalize_academic_unit_key(value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
RETURNS NULL ON NULL INPUT
AS $$
    SELECT lower(regexp_replace(trim(value), '[^[:alnum:]가-힣]+', '', 'g'))
$$;

CREATE TABLE academic_colleges (
    code varchar(40) PRIMARY KEY,
    name varchar(240) NOT NULL,
    normalized_key text GENERATED ALWAYS AS (normalize_academic_unit_key(name)) STORED,
    first_seen_year integer NOT NULL,
    last_seen_year integer NOT NULL,
    is_current boolean NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_academic_colleges_years CHECK (
        first_seen_year BETWEEN 1900 AND 2100
        AND last_seen_year BETWEEN first_seen_year AND 2100
    )
);

CREATE INDEX ix_academic_colleges_normalized_key
    ON academic_colleges (normalized_key);

CREATE TABLE academic_units (
    code varchar(40) PRIMARY KEY,
    college_code varchar(40) REFERENCES academic_colleges(code) ON DELETE RESTRICT,
    name varchar(240) NOT NULL,
    normalized_key text GENERATED ALWAYS AS (normalize_academic_unit_key(name)) STORED,
    code_source varchar(32) NOT NULL,
    first_seen_year integer NOT NULL,
    last_seen_year integer NOT NULL,
    is_current boolean NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_academic_units_years CHECK (
        first_seen_year BETWEEN 1900 AND 2100
        AND last_seen_year BETWEEN first_seen_year AND 2100
    ),
    CONSTRAINT ck_academic_units_code_source CHECK (
        code_source IN ('OFFICIAL_CURRICULUM', 'REQUIREMENT_DERIVED')
    ),
    CONSTRAINT uq_academic_units_normalized_key UNIQUE (normalized_key)
);

CREATE INDEX ix_academic_units_college_code
    ON academic_units (college_code);
CREATE INDEX ix_academic_units_current_name
    ON academic_units (is_current, name);

CREATE TABLE academic_unit_aliases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_unit_code varchar(40) NOT NULL
        REFERENCES academic_units(code) ON DELETE CASCADE,
    alias varchar(240) NOT NULL,
    alias_key text GENERATED ALWAYS AS (normalize_academic_unit_key(alias)) STORED,
    valid_from_year integer,
    valid_to_year integer,
    source_kind varchar(40) NOT NULL,
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_academic_unit_alias_years CHECK (
        (valid_from_year IS NULL OR valid_from_year BETWEEN 1900 AND 2100)
        AND (valid_to_year IS NULL OR valid_to_year BETWEEN 1900 AND 2100)
        AND (
            valid_from_year IS NULL
            OR valid_to_year IS NULL
            OR valid_from_year <= valid_to_year
        )
    ),
    CONSTRAINT uq_academic_unit_alias_source
        UNIQUE NULLS NOT DISTINCT (
            academic_unit_code,
            alias_key,
            valid_from_year,
            valid_to_year,
            source_kind
        )
);

CREATE INDEX ix_academic_unit_aliases_lookup
    ON academic_unit_aliases (alias_key, valid_from_year, valid_to_year);
CREATE INDEX ix_academic_unit_aliases_unit
    ON academic_unit_aliases (academic_unit_code);

CREATE TABLE section_academic_units (
    semester_id varchar(20) NOT NULL,
    course_code varchar(40) NOT NULL,
    section_code varchar(20) NOT NULL,
    academic_unit_code varchar(40) NOT NULL
        REFERENCES academic_units(code) ON DELETE RESTRICT,
    relation_type varchar(24) NOT NULL DEFAULT 'OFFERING',
    source_kind varchar(40) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (
        semester_id,
        course_code,
        section_code,
        academic_unit_code,
        relation_type
    ),
    CONSTRAINT fk_section_academic_units_section
        FOREIGN KEY (semester_id, course_code, section_code)
        REFERENCES sections(semester_id, course_code, section_code)
        ON DELETE CASCADE,
    CONSTRAINT ck_section_academic_units_relation_type CHECK (
        relation_type IN ('OFFERING', 'TARGET', 'CROSS_LISTED')
    )
);

CREATE INDEX ix_section_academic_units_filter
    ON section_academic_units (academic_unit_code, semester_id);
CREATE INDEX ix_section_academic_units_section
    ON section_academic_units (semester_id, course_code, section_code);

ALTER TABLE curriculum_program_requirements
    ADD COLUMN academic_unit_code varchar(40)
        REFERENCES academic_units(code) ON DELETE RESTRICT;
ALTER TABLE graduation_credit_profiles
    ADD COLUMN academic_unit_code varchar(40)
        REFERENCES academic_units(code) ON DELETE RESTRICT;
ALTER TABLE graduation_assessment_profiles
    ADD COLUMN academic_unit_code varchar(40)
        REFERENCES academic_units(code) ON DELETE RESTRICT;
ALTER TABLE graduation_legacy_requirements
    ADD COLUMN academic_unit_code varchar(40)
        REFERENCES academic_units(code) ON DELETE RESTRICT;
ALTER TABLE graduation_requirement_rules
    ADD COLUMN academic_unit_code varchar(40)
        REFERENCES academic_units(code) ON DELETE RESTRICT;

CREATE INDEX ix_curriculum_program_requirements_academic_unit
    ON curriculum_program_requirements (academic_unit_code, admission_year);
CREATE INDEX ix_graduation_credit_profiles_academic_unit
    ON graduation_credit_profiles (academic_unit_code, admission_year);
CREATE INDEX ix_graduation_assessment_profiles_academic_unit
    ON graduation_assessment_profiles (academic_unit_code, effective_year);
CREATE INDEX ix_graduation_legacy_requirements_academic_unit
    ON graduation_legacy_requirements (academic_unit_code, effective_year);
CREATE INDEX ix_graduation_requirement_rules_academic_unit
    ON graduation_requirement_rules (
        academic_unit_code,
        admission_year_start,
        admission_year_end,
        effective_year
    );

COMMENT ON TABLE academic_colleges IS
    'Canonical college codes derived from versioned academic curriculum datasets.';
COMMENT ON TABLE academic_units IS
    'Canonical department, major, and program codes used across catalog and requirement domains.';
COMMENT ON COLUMN academic_units.code_source IS
    'OFFICIAL_CURRICULUM for supplied department codes; REQUIREMENT_DERIVED for deterministic keys without an official code.';
COMMENT ON COLUMN academic_units.is_current IS
    'True when the unit appears in the latest loaded curriculum dataset; not an admissions-status claim.';
COMMENT ON TABLE academic_unit_aliases IS
    'Year-scoped names used to resolve curriculum and graduation-requirement records to canonical units.';
COMMENT ON TABLE section_academic_units IS
    'Many-to-many mapping between catalog sections and explicitly supplied academic-unit contexts.';
