CREATE TABLE timetables (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    semester_id varchar(20) NOT NULL REFERENCES semesters(id) ON DELETE RESTRICT,
    name varchar(120) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_timetables_id_semester UNIQUE (id, semester_id),
    CONSTRAINT ck_timetables_name CHECK (btrim(name) <> '')
);

CREATE INDEX ix_timetables_user_updated
    ON timetables (user_id, updated_at DESC);

CREATE TABLE timetable_courses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timetable_id bigint NOT NULL,
    semester_id varchar(20) NOT NULL,
    course_code varchar(40) NOT NULL,
    section_code varchar(20) NOT NULL,
    course_name varchar(255) NOT NULL,
    professor_name varchar(255),
    credits numeric(5,2) NOT NULL,
    CONSTRAINT uq_timetable_courses_section
        UNIQUE (timetable_id, semester_id, course_code, section_code),
    CONSTRAINT fk_timetable_courses_timetable_semester
        FOREIGN KEY (timetable_id, semester_id)
        REFERENCES timetables(id, semester_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_timetable_courses_section
        FOREIGN KEY (semester_id, course_code, section_code)
        REFERENCES sections(semester_id, course_code, section_code)
        ON DELETE RESTRICT,
    CONSTRAINT ck_timetable_courses_credits CHECK (credits >= 0)
);

CREATE INDEX ix_timetable_courses_timetable
    ON timetable_courses (timetable_id);

CREATE INDEX ix_timetable_courses_section
    ON timetable_courses (semester_id, course_code, section_code);

CREATE TABLE timetable_course_meetings (
    timetable_course_id bigint NOT NULL
        REFERENCES timetable_courses(id) ON DELETE CASCADE,
    position integer NOT NULL,
    day_of_week varchar(20) NOT NULL,
    start_minute smallint NOT NULL,
    end_minute smallint NOT NULL,
    CONSTRAINT pk_timetable_course_meetings
        PRIMARY KEY (timetable_course_id, position),
    CONSTRAINT ck_timetable_course_meetings_position CHECK (position >= 0),
    CONSTRAINT ck_timetable_course_meetings_day CHECK (
        day_of_week IN (
            'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY',
            'FRIDAY', 'SATURDAY', 'SUNDAY'
        )
    ),
    CONSTRAINT ck_timetable_course_meetings_time CHECK (
        start_minute >= 0
        AND start_minute < end_minute
        AND end_minute <= 1440
    )
);

CREATE TABLE optimization_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    timetable_id bigint NOT NULL,
    semester_id varchar(20) NOT NULL,
    status varchar(20) NOT NULL,
    min_credits numeric(5,2) NOT NULL,
    max_credits numeric(5,2) NOT NULL,
    target_credits numeric(5,2) NOT NULL,
    available_start_minute smallint NOT NULL,
    available_end_minute smallint NOT NULL,
    lunch_start_minute smallint NOT NULL,
    lunch_end_minute smallint NOT NULL,
    max_daily_class_minutes integer NOT NULL,
    failure_reason varchar(255),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_optimization_jobs_id_semester UNIQUE (id, semester_id),
    CONSTRAINT fk_optimization_jobs_timetable_semester
        FOREIGN KEY (timetable_id, semester_id)
        REFERENCES timetables(id, semester_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_optimization_jobs_status CHECK (
        status IN ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'TIMEOUT', 'CANCELLED')
    ),
    CONSTRAINT ck_optimization_jobs_credits CHECK (
        min_credits >= 0
        AND min_credits <= target_credits
        AND target_credits <= max_credits
    ),
    CONSTRAINT ck_optimization_jobs_available_time CHECK (
        available_start_minute >= 0
        AND available_start_minute < available_end_minute
        AND available_end_minute <= 1440
    ),
    CONSTRAINT ck_optimization_jobs_lunch_time CHECK (
        lunch_start_minute >= 0
        AND lunch_start_minute < lunch_end_minute
        AND lunch_end_minute <= 1440
    ),
    CONSTRAINT ck_optimization_jobs_daily_minutes CHECK (
        max_daily_class_minutes > 0
    )
);

CREATE INDEX ix_optimization_jobs_user_created
    ON optimization_jobs (user_id, created_at DESC);

CREATE INDEX ix_optimization_jobs_timetable
    ON optimization_jobs (timetable_id);

CREATE TABLE optimization_job_excluded_days (
    job_id bigint NOT NULL REFERENCES optimization_jobs(id) ON DELETE CASCADE,
    day_of_week varchar(20) NOT NULL,
    CONSTRAINT pk_optimization_job_excluded_days
        PRIMARY KEY (job_id, day_of_week),
    CONSTRAINT ck_optimization_job_excluded_days_day CHECK (
        day_of_week IN (
            'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY',
            'FRIDAY', 'SATURDAY', 'SUNDAY'
        )
    )
);

CREATE TABLE optimization_job_required_sections (
    job_id bigint NOT NULL,
    semester_id varchar(20) NOT NULL,
    course_code varchar(40) NOT NULL,
    section_code varchar(20) NOT NULL,
    CONSTRAINT pk_optimization_job_required_sections
        PRIMARY KEY (job_id, semester_id, course_code, section_code),
    CONSTRAINT fk_optimization_required_job_semester
        FOREIGN KEY (job_id, semester_id)
        REFERENCES optimization_jobs(id, semester_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_optimization_required_section
        FOREIGN KEY (semester_id, course_code, section_code)
        REFERENCES sections(semester_id, course_code, section_code)
        ON DELETE RESTRICT
);

CREATE TABLE optimization_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL REFERENCES optimization_jobs(id) ON DELETE CASCADE,
    rank integer NOT NULL,
    attendance_days integer NOT NULL,
    total_credits numeric(5,2) NOT NULL,
    total_free_minutes integer NOT NULL,
    score double precision NOT NULL,
    CONSTRAINT uq_optimization_results_job_rank UNIQUE (job_id, rank),
    CONSTRAINT ck_optimization_results_rank CHECK (rank > 0),
    CONSTRAINT ck_optimization_results_metrics CHECK (
        attendance_days >= 0
        AND total_credits >= 0
        AND total_free_minutes >= 0
    )
);

CREATE INDEX ix_optimization_results_job
    ON optimization_results (job_id);

CREATE TABLE optimization_result_course_slots (
    result_id bigint NOT NULL REFERENCES optimization_results(id) ON DELETE CASCADE,
    position integer NOT NULL,
    semester_id varchar(20) NOT NULL,
    course_code varchar(40) NOT NULL,
    section_code varchar(20) NOT NULL,
    course_name varchar(255) NOT NULL,
    professor_name varchar(255),
    credits numeric(5,2) NOT NULL,
    day_of_week varchar(20) NOT NULL,
    start_minute smallint NOT NULL,
    end_minute smallint NOT NULL,
    CONSTRAINT pk_optimization_result_course_slots
        PRIMARY KEY (result_id, position),
    CONSTRAINT fk_optimization_result_section
        FOREIGN KEY (semester_id, course_code, section_code)
        REFERENCES sections(semester_id, course_code, section_code)
        ON DELETE RESTRICT,
    CONSTRAINT ck_optimization_result_slots_position CHECK (position >= 0),
    CONSTRAINT ck_optimization_result_slots_credits CHECK (credits >= 0),
    CONSTRAINT ck_optimization_result_slots_day CHECK (
        day_of_week IN (
            'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY',
            'FRIDAY', 'SATURDAY', 'SUNDAY'
        )
    ),
    CONSTRAINT ck_optimization_result_slots_time CHECK (
        start_minute >= 0
        AND start_minute < end_minute
        AND end_minute <= 1440
    )
);

CREATE INDEX ix_optimization_result_slots_section
    ON optimization_result_course_slots (semester_id, course_code, section_code);

COMMENT ON TABLE timetables IS
    '사용자별 학기 시간표. users UUID와 semesters 정식 키를 참조한다.';
COMMENT ON TABLE timetable_courses IS
    '시간표에 선택된 분반과 표시용 학사 스냅샷.';
COMMENT ON TABLE timetable_course_meetings IS
    '선택 분반의 수업시간 스냅샷. 원본 sessions는 학사 카탈로그에 유지된다.';
COMMENT ON TABLE optimization_jobs IS
    '자동 편성 요청 조건과 비동기 처리 상태.';
COMMENT ON TABLE optimization_job_required_sections IS
    '자동 편성에서 반드시 포함할 정확한 학기·강의·분반 키.';
COMMENT ON TABLE optimization_results IS
    '자동 편성 작업에서 선택된 상위 결과.';
COMMENT ON TABLE optimization_result_course_slots IS
    '자동 편성 결과의 분반별 수업시간 스냅샷.';
