ALTER TABLE courses
    ADD COLUMN lecture_hours numeric(5, 2),
    ADD COLUMN practice_hours numeric(5, 2);

ALTER TABLE courses
    ADD CONSTRAINT ck_courses_lecture_hours
        CHECK (lecture_hours IS NULL OR lecture_hours >= 0),
    ADD CONSTRAINT ck_courses_practice_hours
        CHECK (practice_hours IS NULL OR practice_hours >= 0);

ALTER TABLE sections
    ADD COLUMN target_grade varchar(40),
    ADD COLUMN capacity integer,
    ADD COLUMN notes text,
    ADD COLUMN raw_location text,
    ADD COLUMN source_page integer,
    ADD COLUMN source_row integer,
    ADD COLUMN source_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE sections
    ADD CONSTRAINT ck_sections_capacity
        CHECK (capacity IS NULL OR capacity >= 0),
    ADD CONSTRAINT ck_sections_source_page
        CHECK (source_page IS NULL OR source_page > 0),
    ADD CONSTRAINT ck_sections_source_row
        CHECK (source_row IS NULL OR source_row > 0);

ALTER TABLE sessions
    ADD COLUMN sequence_no smallint;

WITH numbered_sessions AS (
    SELECT
        id,
        row_number() OVER (
            PARTITION BY semester_id, course_code, section_code
            ORDER BY day, start_minute, end_minute, id
        )::smallint AS sequence_no
    FROM sessions
)
UPDATE sessions
SET sequence_no = numbered_sessions.sequence_no
FROM numbered_sessions
WHERE sessions.id = numbered_sessions.id;

ALTER TABLE sessions
    ALTER COLUMN sequence_no SET NOT NULL,
    ADD CONSTRAINT ck_sessions_sequence_no CHECK (sequence_no > 0),
    ADD CONSTRAINT uq_sessions_section_sequence
        UNIQUE (semester_id, course_code, section_code, sequence_no),
    ADD CONSTRAINT uq_sessions_id_semester UNIQUE (id, semester_id);

CREATE TABLE session_rooms (
    session_id bigint NOT NULL,
    semester_id varchar(20) NOT NULL,
    room_code varchar(40) NOT NULL,
    position smallint NOT NULL,
    PRIMARY KEY (session_id, position),
    CONSTRAINT fk_session_rooms_session
        FOREIGN KEY (session_id, semester_id)
        REFERENCES sessions(id, semester_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_session_rooms_room
        FOREIGN KEY (semester_id, room_code)
        REFERENCES rooms(semester_id, code)
        ON DELETE CASCADE,
    CONSTRAINT ck_session_rooms_position CHECK (position > 0),
    CONSTRAINT uq_session_rooms_room
        UNIQUE (session_id, semester_id, room_code)
);

INSERT INTO session_rooms (session_id, semester_id, room_code, position)
SELECT id, semester_id, room_code, 1
FROM sessions
WHERE room_code IS NOT NULL;

CREATE INDEX ix_session_rooms_room
    ON session_rooms (semester_id, room_code);

CREATE TABLE catalog_sources (
    checksum varchar(64) PRIMARY KEY,
    semester_id varchar(20) NOT NULL
        REFERENCES semesters(id) ON DELETE CASCADE,
    source_kind varchar(40) NOT NULL,
    original_file_name text NOT NULL,
    published_on date,
    parser_version varchar(40) NOT NULL,
    raw_row_count integer NOT NULL,
    unique_section_count integer NOT NULL,
    imported_at timestamptz NOT NULL DEFAULT now(),
    metadata jsonb NOT NULL,
    CONSTRAINT ck_catalog_sources_checksum
        CHECK (checksum ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_catalog_sources_counts
        CHECK (
            raw_row_count >= 0
            AND unique_section_count >= 0
            AND unique_section_count <= raw_row_count
        )
);

CREATE INDEX ix_catalog_sources_semester
    ON catalog_sources (semester_id);

CREATE TABLE catalog_source_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_checksum varchar(64) NOT NULL
        REFERENCES catalog_sources(checksum) ON DELETE CASCADE,
    semester_id varchar(20) NOT NULL,
    course_code varchar(40) NOT NULL,
    section_code varchar(20) NOT NULL,
    page_number integer NOT NULL,
    row_number integer NOT NULL,
    context_label text NOT NULL,
    is_shaded boolean NOT NULL DEFAULT false,
    raw_cells jsonb NOT NULL,
    CONSTRAINT fk_catalog_source_rows_section
        FOREIGN KEY (semester_id, course_code, section_code)
        REFERENCES sections(semester_id, course_code, section_code)
        ON DELETE CASCADE,
    CONSTRAINT ck_catalog_source_rows_page CHECK (page_number > 0),
    CONSTRAINT ck_catalog_source_rows_row CHECK (row_number > 0),
    CONSTRAINT uq_catalog_source_rows_locator
        UNIQUE (source_checksum, page_number, row_number)
);

CREATE INDEX ix_catalog_source_rows_section
    ON catalog_source_rows (semester_id, course_code, section_code);

CREATE TABLE section_classification_contexts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester_id varchar(20) NOT NULL,
    course_code varchar(40) NOT NULL,
    section_code varchar(20) NOT NULL,
    source_checksum varchar(64) NOT NULL
        REFERENCES catalog_sources(checksum) ON DELETE CASCADE,
    context_label text NOT NULL,
    context_kind varchar(40) NOT NULL,
    academic_unit_code varchar(40)
        REFERENCES academic_units(code) ON DELETE RESTRICT,
    completion_category varchar(40),
    target_grade varchar(40),
    is_primary boolean NOT NULL DEFAULT false,
    is_shaded boolean NOT NULL DEFAULT false,
    source_page integer NOT NULL,
    source_row integer NOT NULL,
    CONSTRAINT fk_section_classification_contexts_section
        FOREIGN KEY (semester_id, course_code, section_code)
        REFERENCES sections(semester_id, course_code, section_code)
        ON DELETE CASCADE,
    CONSTRAINT ck_section_classification_context_kind CHECK (
        context_kind IN (
            'ACADEMIC_UNIT',
            'GENERAL_EDUCATION',
            'GENERAL_EDUCATION_AREA',
            'TEACHING',
            'GENERAL_ELECTIVE',
            'OTHER'
        )
    ),
    CONSTRAINT ck_section_classification_source_page CHECK (source_page > 0),
    CONSTRAINT ck_section_classification_source_row CHECK (source_row > 0),
    CONSTRAINT uq_section_classification_source
        UNIQUE (
            source_checksum,
            semester_id,
            course_code,
            section_code,
            source_page,
            source_row
        )
);

CREATE INDEX ix_section_classification_section
    ON section_classification_contexts (
        semester_id,
        course_code,
        section_code
    );

CREATE INDEX ix_section_classification_academic_unit
    ON section_classification_contexts (
        academic_unit_code,
        semester_id
    )
    WHERE academic_unit_code IS NOT NULL;

COMMENT ON COLUMN courses.lecture_hours IS
    'Official scheduled lecture-hour value for this semester course.';
COMMENT ON COLUMN courses.practice_hours IS
    'Official scheduled practice-hour value for this semester course.';
COMMENT ON COLUMN sections.source_snapshot IS
    'Normalized official source row used to build the canonical section.';
COMMENT ON TABLE session_rooms IS
    'Ordered many-to-many rooms used by a normalized meeting. sessions.room_code remains the primary room for compatibility.';
COMMENT ON TABLE catalog_sources IS
    'Immutable provenance for an official catalog source file and parser run.';
COMMENT ON TABLE catalog_source_rows IS
    'Lossless source rows, including duplicate cross-listing rows, page locators, shading, and raw cells.';
COMMENT ON TABLE section_classification_contexts IS
    'Context-specific completion category and target grade for a section as printed under departments, programs, or liberal-education areas.';
