CREATE TABLE optimization_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    timetable_id bigint NOT NULL,
    status varchar(20) NOT NULL,
    min_credit integer NOT NULL,
    max_credit integer NOT NULL,
    target_credit integer NOT NULL,
    available_time_start time NOT NULL,
    available_time_end time NOT NULL,
    lunch_time_start time NOT NULL,
    lunch_time_end time NOT NULL,
    max_daily_class_minutes integer NOT NULL,
    failure_reason varchar(255),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_optimization_jobs_status CHECK (
        status IN ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'TIMEOUT', 'CANCELLED')
    )
);

CREATE INDEX ix_optimization_jobs_user_id ON optimization_jobs (user_id);
CREATE INDEX ix_optimization_jobs_timetable_id ON optimization_jobs (timetable_id);

CREATE TABLE optimization_job_excluded_days (
    job_id bigint NOT NULL REFERENCES optimization_jobs(id) ON DELETE CASCADE,
    day_of_week varchar(20) NOT NULL,
    CONSTRAINT pk_optimization_job_excluded_days PRIMARY KEY (job_id, day_of_week),
    CONSTRAINT ck_optimization_job_excluded_days_day CHECK (
        day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
    )
);

CREATE TABLE optimization_job_required_courses (
    job_id bigint NOT NULL REFERENCES optimization_jobs(id) ON DELETE CASCADE,
    course_id bigint NOT NULL,
    CONSTRAINT pk_optimization_job_required_courses PRIMARY KEY (job_id, course_id)
);

CREATE TABLE optimization_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL REFERENCES optimization_jobs(id) ON DELETE CASCADE,
    rank integer NOT NULL,
    attendance_days integer NOT NULL,
    total_credits integer NOT NULL,
    total_free_minutes integer NOT NULL,
    score double precision NOT NULL
);

CREATE INDEX ix_optimization_results_job_id ON optimization_results (job_id);

CREATE TABLE optimization_result_course_slots (
    result_id bigint NOT NULL REFERENCES optimization_results(id) ON DELETE CASCADE,
    course_id bigint,
    course_name varchar(255),
    professor_name varchar(255),
    credit integer,
    day_of_week varchar(20),
    start_time time,
    end_time time,
    CONSTRAINT ck_optimization_result_course_slots_day CHECK (
        day_of_week IS NULL OR day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
    )
);

CREATE INDEX ix_optimization_result_course_slots_result_id
    ON optimization_result_course_slots (result_id);

COMMENT ON TABLE optimization_jobs IS
    '자동 시간표 편성 요청 조건과 상태. 후보 강의 목록 자체는 영속화하지 않는다.';
COMMENT ON TABLE optimization_job_excluded_days IS
    'OptimizationJob.excludedDays 요소 컬렉션(@ElementCollection Set<DayOfWeek>).';
COMMENT ON TABLE optimization_job_required_courses IS
    'OptimizationJob.requiredCourseIds 요소 컬렉션(@ElementCollection Set<Long>).';
COMMENT ON TABLE optimization_results IS
    '편성 작업이 산출한 상위 시간표 조합 하나에 대한 결과 스냅샷.';
COMMENT ON TABLE optimization_result_course_slots IS
    'OptimizationResult.courseSlots 요소 컬렉션(@ElementCollection List<CourseSlot>).';
