CREATE TABLE course_sequence_hints (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prerequisite_course_code varchar(40) NOT NULL,
    follow_up_course_code varchar(40) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_course_sequence_hints_not_self_referencing CHECK (
        prerequisite_course_code <> follow_up_course_code
    ),
    CONSTRAINT uq_course_sequence_hints_pair
        UNIQUE (prerequisite_course_code, follow_up_course_code)
);

CREATE INDEX ix_course_sequence_hints_follow_up
    ON course_sequence_hints (follow_up_course_code);

COMMENT ON TABLE course_sequence_hints IS
    'Manually curated prerequisite/follow-up course code pairs used only as a soft
     scheduling hint. Not an official prerequisite system and not validated against
     courses or curriculum_required_courses — course codes are free-standing, the
     same way curriculum_required_courses.course_code has no FK to courses, because
     a code is reused across many semester offerings.';

-- 기초미적분학(005111) 이수 후 응용미적분학(005112)/공업수학II(924011)로 이어지는
-- 통상적인 이수 순서를 수동으로 큐레이션한 초기 데이터.
INSERT INTO course_sequence_hints (prerequisite_course_code, follow_up_course_code)
VALUES
    ('005111', '005112'),
    ('005111', '924011');
